part of 'package:mdrawer/app/core/theme/theme.dart';

ThemeData get darkTheme => ThemeData.dark().copyWith(
      brightness: Brightness.dark,
      scaffoldBackgroundColor: Palette.gray[900],
      appBarTheme: AppBarTheme(
        backgroundColor: Palette.gray[800],
      ),
      // visualDensity: ,
      // primaryColor: ,
      // primaryColorLight:,
      // primaryColorDark:,
      // accentColor:,
      // accentColorBrightness:,
      // canvasColor:,
      // shadowColor:,
      // bottomAppBarColor:,
      // cardColor:,
      // dividerColor:,
      // focusColor:,
      // hoverColor:,
      // highlightColor:,
      // splashColor:,
      // splashFactory:,
      // selectedRowColor:,
      // unselectedWidgetColor:,
      // disabledColor:,
      // buttonTheme:,
      // toggleButtonsTheme:,
      // buttonColor:,
      // secondaryHeaderColor:,
      // textSelectionColor:,
      // cursorColor:,
      // textSelectionHandleColor,
      // backgroundColor:,
      // dialogBackgroundColor:,
      // indicatorColor:,
      // hintColor:,
      // errorColor:,
      // toggleableActiveColor:,
      // textTheme:,
      // primaryTextTheme:,
      // accentTextTheme:,
      // inputDecorationTheme:,
      // iconTheme:,
      // primaryIconTheme:,
      // accentIconTheme:,
      // sliderTheme:,
      // tabBarTheme:,
      // tooltipTheme:,
      // cardTheme:,
      // chipTheme:,
      // platform:,
      // materialTapTargetSize:,
      // applyElevationOverlayColor:,
      // pageTransitionsTheme:,
      // scrollbarTheme:,
      // bottomAppBarTheme:,
      // colorScheme:,
      // dialogTheme:,
      // floatingActionButtonTheme:,
      // navigationRailTheme:,
      // typography:,
      // cupertinoOverrideTheme:,
      // snackBarTheme:,
      // bottomSheetTheme:,
      // popupMenuTheme:,
      // bannerTheme:,
      // dividerTheme:,
      // buttonBarTheme:,
      // bottomNavigationBarTheme:,
      // timePickerTheme:,
      // textButtonTheme:,
      // elevatedButtonTheme:,
      // outlinedButtonTheme:,
      // textSelectionTheme:,
      // dataTableTheme:,
      // checkboxTheme: CheckboxThemeData(
      // mouseCursor:,
      // fillColor: ,
      // checkColor:,
      // overlayColor:,
      // splashRadius:,
      // materialTapTargetSize:,
      // visualDensity:,
      // shape:,
      // side:,
      // ),
      // radioTheme:,
      // switchTheme:,
      // progressIndicatorTheme:,
      // fixTextFieldOutlineLabel:,
      // useTextSelectionTheme:,
    );
